In [1]:
import pandas as pd
from google.colab import files
uploaded=files.upload()

Saving bestsellers with categories.csv to bestsellers with categories.csv


In [5]:
import io
df=pd.read_csv(io.BytesIO(uploaded['bestsellers with categories.csv']))
df.head()

Name  ...        Genre
0                      10-Day Green Smoothie Cleanse  ...  Non Fiction
1                                  11/22/63: A Novel  ...      Fiction
2            12 Rules for Life: An Antidote to Chaos  ...  Non Fiction
3                             1984 (Signet Classics)  ...      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  ...  Non Fiction

[5 rows x 7 columns]

Examples of using **Numpy**

In [3]:
import numpy as np

arr=[int (i) for i in input().split()]
arr =np.array(arr)
arr


1 2 5 2 5
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
a=np.array(10)
b=np.array([1,2,3,4,5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


# **Using Pandas**

---



In [8]:
import pandas as pd
import numpy as np


In [9]:
data=[1,2,3,4,5]
df=pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [10]:
data=[['Alex',10],['Bob',15],['Marley',20]]
df=pd.DataFrame(data)
df

0   1
0    Alex  10
1     Bob  15
2  Marley  20

In [11]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [14]:

dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [15]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.777223  0.081687 -0.064840  0.133115
2013-01-02 -0.341469  1.609822 -0.734884 -1.824171
2013-01-03  0.558391  1.054313 -1.246243  1.394785
2013-01-04 -1.524255  0.224238 -0.333386 -1.517520
2013-01-05 -0.871505  0.856523  0.117442 -0.029581
2013-01-06  0.666632 -0.827357  0.618200  0.115140

In [16]:
df2 = pd.DataFrame({'A': 1.,'B': pd.Timestamp('20130102'),'C': pd.Series(1, index=list(range(4)), dtype='float32'),'D': np.array([3] * 4, dtype='int32'),'E': pd.Categorical(["test", "train", "test", "train"]),'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [17]:
df.head()

A         B         C         D
2013-01-01  0.777223  0.081687 -0.064840  0.133115
2013-01-02 -0.341469  1.609822 -0.734884 -1.824171
2013-01-03  0.558391  1.054313 -1.246243  1.394785
2013-01-04 -1.524255  0.224238 -0.333386 -1.517520
2013-01-05 -0.871505  0.856523  0.117442 -0.029581

In [18]:
df.tail(3)

A         B         C         D
2013-01-04 -1.524255  0.224238 -0.333386 -1.517520
2013-01-05 -0.871505  0.856523  0.117442 -0.029581
2013-01-06  0.666632 -0.827357  0.618200  0.115140

In [19]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0